### ISSUE TITLE
Where can I download the weights for the 1.1B model?

### ISSUE THREAD

**Issue by Zeyu1226-mt** [XiaoduoAILab/XmodelLM#1]
In generate.py: 
parser.add_argument("--model_path", type=str, default="", help="")

Where is the weight of model path downloaded?

**Comment by wyyccc** [comment]
It depends on where you downloaded the model files to. If you haven't downloaded yet, you can download it here: https://huggingface.co/XiaoduoAILab/Xmodel_LM!

**Comment by Zeyu1226-mt** [comment]
thank you&nbsp;



发自我的iPhone


------------------ Original ------------------
From: grey wang ***@***.***&gt;
Date: Thu,Jun 13,2024 10:17 AM
To: XiaoduoAILab/XmodelLM ***@***.***&gt;
Cc: 习泽宇 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [XiaoduoAILab/XmodelLM] Where can I download the weights for the1.1B model? (Issue #1)





 
It depends on where you downloaded the model files to. If you haven't downloaded yet, you can download it here: https://huggingface.co/XiaoduoAILab/Xmodel_LM!
