### ISSUE TITLE
How to train this code on my own dataset to achieve the task of video captioning???

### ISSUE THREAD

**Issue by Zeyu1226-mt** [XiaoduoAILab/XmodelLM#2]
Hello, it is a very meaningful work. I want to knowledge how can i train this code on my own dataset to achieve the task of video captioning?

**Comment by ValeriaWong** [comment]
Hello,

Thank you for your interest and kind words! We’re glad to hear from you. Our model is a pure language-based large model, so it doesn’t directly handle video captioning tasks. However, if you’d like to explore training for video captioning, we recommend referring to multimodal research. You can find our work on multimodal tasks, which might be helpful for your needs, at the following link: https://github.com/XiaoduoAILab/XmodelVLM.

Feel free to reach out if you have more questions!

Best regards,
ValeriaWong
